# Generated by Django 3.2.3 on 2021-06-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_datoszapatilla_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rutColaborador', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut de Colaborador')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='colaborador/')),
                ('nombreCompleto', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=200, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de País')),
                ('nombrePais', models.CharField(max_length=100, verbose_name='nombre de País')),
            ],
        ),
        migrations.DeleteModel(
            name='DatosZapatilla',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
    ]
