# Generated by Django 3.2.3 on 2021-06-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210627_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pais',
            new_name='Paises',
        ),
    ]
